### ISSUE TITLE
how to implement LOCK

### ISSUE THREAD

**Issue by techzhou** [miltonio/milton2#105]
I use anno

```Java
@ResourceController
public class WebdavController {
    private URI projectBase = null;

    @AccessControlList
    public List<AccessControlledResource.Priviledge> getPriviledges(File target, String currentUser ) {
        return AccessControlledResource.READ_WRITE;
    }

    @Root
    public WebdavController getRoot() {
        return this;
    }

    @Get
    public InputStream getFile(File f) throws IOException {
        return FileUtils.openInputStream(f);
    }

    @ChildrenOf
    public Collection<File> getUploads(WebdavController root) {
        return FileUtils.listFiles(xxxxx);
    }

    @PutChild
    public File upload(File f, String newName, byte[] bytes) {
        return f;
    }

    @UniqueId
    public long getUUID(File f) {
        return 10L;
    }
```

> <filter>
        <filter-name>MiltonFilter</filter-name>
        <filter-class>io.milton.servlet.MiltonFilter</filter-class>
        <init-param>
            <param-name>resource.factory.class</param-name>
            <param-value>io.milton.http.annotated.AnnotationResourceFactory</param-value>
        </init-param>
        <init-param>
            <param-name>controllerPackagesToScan</param-name>
            <param-value>cn.myapps.core.webdav</param-value>
        </init-param>
        <init-param>
            <param-name>contextPath</param-name>
            <param-value>/dav</param-value>
        </init-param>
        <init-param>
            <param-name>extraAuthenticationHandlers</param-name>
            <param-value>cn.myapps.core.webdav.TokenAuthenticationHandler</param-value>
        </init-param>
        <init-param>
            <param-name>enableBasicAuth</param-name>
            <param-value>false</param-value>
        </init-param>
        <init-param>
            <param-name>enableDigestAuth</param-name>
            <param-value>false</param-value>
        </init-param>
    </filter>

when I try LOCK http://xxxxx/dav/abc.docx, I got http 501

**Comment by bradmac** [comment]
Hi,

Please make sure you're using the milton enterprise edition 
(milton-server-ent) and that the license validation is working 
correctly. You can check the startup logs to confirm license validation.

BTW, Milton already has an implementation for browsing files. This is 
actually enabled by default, so if you dont do anything at all milton 
will start a file based dav server.

Regards,

Brad

**Comment by techzhou** [comment]
thank you 👍
