### ISSUE TITLE
Cannot open milton-ce in read-write mode

### ISSUE THREAD

**Issue by sarnobat** [miltonio/milton2#108]
I've tried debugging it without success, using the SimpletonStarter and the embedded web server. My Mac Finder interface just displays it as a read-only resource.

**Comment by bradmac** [comment]
Note that LOCK support is required for native OS clients, and you need milton enterprise to have lock support.

The simple reference examples are not intended to work with native OS clients. If you just want to demo and play around use 3rd party clients like Cyberduck.

If you want to see Milton working with native OS clients please obtain a trial license here - http://milton.io/milton-store/milton2-trial/

Update your project to include the milton-server-ent jar and check that the license validation is processed correctly on startup

**Comment by sarnobat** [comment]
Thank you very much for the quick response. I wasn't sure whether locking was required but this confirms it is.
