### ISSUE TITLE
example project  "milton-anno-bandstand" doesn't work as shown in the video

### ISSUE THREAD

**Issue by SageAgastya** [miltonio/milton2#109]
Hi,
I'm exploring how webdav works in Milton when accesses from browser, webDav mac client.
Checked out this example project. Had hard time compiling the project.
   
Now jetty is started however i see the following issues.

1) http://localhost:8080/bands/DestinysChild url doesn't work anymore? (Shown in the video)
2) http://localhost:8080 works from google chrome browser. But not from Finder in mac. ( accessing remote server)

I'd like to try uploading files/viewing files etc ..

Could you help me with some example project that works.

Cheers,
Phaneendra

**Comment by bradmac** [comment]
Hey,
Please follow the tutorials - http://milton.io/tutorials.html

- The folder for Destiny's Child will only be available if you run the app and create a band with that name. The project is intended to show integrating dav into a database driven application
- this example application does not have the enterprise editiion jars which are required to work with major OS clients such as Mac Finder
