### ISSUE TITLE
Does version 2.7.4.4 is correct build?

### ISSUE THREAD

**Issue by Java-class** [miltonio/milton2#111]
Hello. I'm trying to build and deploy Milton version 2.7.4.4 in my Java WebDAV Application, my question is in the home page of the milton2 project under the file structure there is a build-error tag show, is this mention that builds of this version is a failure?
I appreciate  Milton's developer help me.

**Comment by bradmac** [comment]
Yep, its all good. I think thats from a CI script a contributor provided which does checks on old java versions. I dont think its a significant error

**Comment by Java-class** [comment]
Thank you for your good answering.

>
