### ISSUE TITLE
BeanPropertyResource does not work for AnnoCollectionResources?

### ISSUE THREAD

**Issue by niriak** [miltonio/milton2#115]
Looks like resources marked with @BeanPropertyResource does not work when using AnnotationResourceFactory (e.g. PROPPATCH does not find any property getter/setter).

May be there should be _bean_ instead of _r_ in Line 139 of [io.milton.property.BeanPropertySource](../tree/master/milton-server-ce/src/main/java/io/milton/property/BeanPropertySource.java) ?

**Comment by bradmac** [comment]
yes, BeanPropertySource was never intended to work with annotated resources

I guess it would be trivial to do an instanceof condition to check for a AnnoResource, and if so to cast it and call getSource()

Would you like to send a pull request?

**Comment by niriak** [comment]
Added PR #116

**Comment by bradmac** [comment]
Aha, sorry yes you were right. Perfect :)
