### ISSUE TITLE
ERROR: Failed to resolve: io.milton:aspirin:0.10.03.03

### ISSUE THREAD

**Issue by letruonglamit** [miltonio/milton2#120]
I received an error when add milton-server-ce in android gradle: 

implementation group: 'io.milton', name: 'milton-server-ce', version: '2.7.1.7'

ERROR: Failed to resolve: io.milton:aspirin:0.10.03.03

How to resolve it?

**Comment by bradmac** [comment]
Hey, that aspirin dependency should be fine, not sure why its not resolving for you

You can get it manually from the bintray repo:
https://bintray.com/milton/Milton/milton#files/io%2Fmilton%2Faspirin%2F0.10.03.03

**Comment by ophiuhus** [comment]
All the aspirin dependencies now in the main maven repo
