### ISSUE TITLE
2.8.0.x < 2.8.0.2 no longer available on mvnrepository.com

### ISSUE THREAD

**Issue by BartRobeyns** [miltonio/milton2#154]
We are running into the issue #140, and  we will of course ask for the new license, but we are blocked right now because the 2.8.0.x versions < 2.8.0.2 are no longer available from the maven repositories. So we can't build with 2.8.0.0, but we can't upgrade to 2.8.0.3 because of the license issue.
Can you make the 2.8.0.0 available again?

(The maven repo page for milton-api 2.8.0.0 points to https://dl.bintray.com/milton/Milton/io/milton/milton-api/2.8.0.0/milton-api-2.8.0.0.jar, which returns 403 Forbidden).

**Comment by VolodymyrLychman** [comment]
Hi Bart,

Thank you for your request. We have purchased Milton last year and have
immediately moved to Maven Central repository. Unfortunately we can move
only new artifacts. The bin tray is discontinued and old versions are
unavailable.
As far as I remember you can build artifacts from source codes. Please
submit your request to our help and support Center, so our developers can
help you.

**Comment by BartRobeyns** [comment]
Thanks for the explanation. We've almost got the new license, and wait for that one. Was primarily curious about the disappearance of 2.8.0.0
