### ISSUE TITLE
Wrong website content

### ISSUE THREAD

**Issue by alialbaali** [miltonio/milton2#163]
I think the second code image should be marked "Without annotations" and not "With annotations", right?

![image](https://user-images.githubusercontent.com/37933889/146495603-45689540-ef04-4455-8306-f728a7578bae.png)

**Comment by ophiuhus** [comment]
@alialbaali , can you provide a link where you see it?
Thanks

**Comment by alialbaali** [comment]
On this [link](https://milton.io)

**Comment by ophiuhus** [comment]
Thanks
