### ISSUE TITLE
Inconsistent behavior on return valut of CollectionResource#getChildren

### ISSUE THREAD

**Issue by kofemann** [miltonio/milton2#184]
The `CollectionResource#getChildren()`  is a collection of child resources. Some paths of code
expect  that the returned value can be `null`

https://github.com/miltonio/milton2/blob/master/milton-server-ce/src/main/java/io/milton/http/webdav/DefaultPropFindPropertyBuilder.java#L182
```java
			List<? extends Resource> list = col.getChildren();
			if (list != null) {
```

However, the other parts of the code fail with NPE if the returned value is `null`:
https://github.com/miltonio/milton2/blob/master/milton-server-ce/src/main/java/io/milton/http/DeleteHelperImpl.java#L64
```java
		} else if (r instanceof CollectionResource) {
			CollectionResource col = (CollectionResource) r;
            List<Resource> list = new ArrayList<>(col.getChildren());
```

```
java.lang.NullPointerException: null
	at java.base/java.util.ArrayList.addAll(ArrayList.java:702)
	at io.milton.http.DeleteHelperImpl.isLockedOut(DeleteHelperImpl.java:65)
	at io.milton.http.http11.DeleteHandler.processExistingResource(DeleteHandler.java:92)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:131)
	at io.milton.http.http11.DeleteHandler.processResource(DeleteHandler.java:83)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
	at org.dcache.webdav.DcacheResourceHandlerHelper.process(DcacheResourceHandlerHelper.java:42)
```

Unfortunately, the javadoc of the  CollectionResource doesn't say what callers should expect. The current state is contradicting 
and broken.

**Comment by ophiuhus** [comment]
Which Java version do you use?
What I see here is
java.lang.NullPointerException: null
	at java.base/java.util.ArrayList.addAll(ArrayList.java:702)
Array list throws an error on addAll. 
Constructor of ArrayList doesn't use addAll - at least in recent versions of Java.
DeleteHelperImpl doesn't use any addAll calls.
I suspect it might be somewhere inside your CollectionResource implementation

**Comment by kofemann** [comment]
java 11. Indeed, the constructor doesn't use `addAll`, but:

```java
    public ArrayList(Collection<? extends E> c) {
        Object[] a = c.toArray();
        if ((size = a.length) != 0) {
```

Thus, `c.toArray()` will fail with NPE, if `c` is a `null`.

**Comment by kofemann** [comment]
and if you look at the javadoc, then ist clearly stated:

```
   /**
     * Constructs a list containing the elements of the specified
     * collection, in the order they are returned by the collection's
     * iterator.
     *
     * @param c the collection whose elements are to be placed into this list
     * @throws NullPointerException if the specified collection is null
     */
```

**Comment by ophiuhus** [comment]
Yes, I agree with javadoc. But what's confusing me - is the stacktrace
java.lang.NullPointerException: null
	at java.base/java.util.ArrayList.addAll(ArrayList.java:702)
Why there is addAll?
I'm trying to reproduce it
List<? extends String> list = new ArrayList<>(null);
        for (String s : list) {
            System.out.println(s);
        }
Here small code
It gives different trace
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.ArrayList.<init>(ArrayList.java:179)
	at Main.main(Main.java:6)

**Comment by kofemann** [comment]
we use milton 2.7.3

**Comment by ophiuhus** [comment]
It doesn't reject the fact it fails not on the constructor, but on the addAll method.
Can you check you CollectionResource implementation - the getChildren method - if it executes somewhere addAll?

**Comment by kofemann** [comment]
In tag 2.7.3 code looks like this:

```java
		} else if (r instanceof CollectionResource) {
			CollectionResource col = (CollectionResource) r;
			List<Resource> list = new ArrayList<Resource>();
			list.addAll(col.getChildren());
```
https://github.com/miltonio/milton2/blob/2.7.3.0/milton-server-ce/src/main/java/io/milton/http/DeleteHelperImpl.java#LL62-L65C35

**Comment by ophiuhus** [comment]
Ok, now I see, it was refactored a while ago. 
Thanks.
But the changes will be available only in master branch, meaning - only for new versions.
You can update your implementation of CollectionResource to not return null but empty collection.

**Comment by ophiuhus** [comment]
Added check for null pointer
