### ISSUE TITLE
Missing HTTP status code 429

### ISSUE THREAD

**Issue by kofemann** [miltonio/milton2#193]
Some backends prefer to return HTTP status code 429 in case of too many requests, as  defined in 
[RFC 6585](https://www.rfc-editor.org/rfc/rfc6585.html#page-3). Unfortunately, the Milton2 library doesn't specify such code, which forces implementors to introduce some workarounds. Thus, providing a way to return `too many requests` error will simplify backend implementations and integration with milton library.

**Comment by ophiuhus** [comment]
https://github.com/miltonio/milton2/commit/f208ab399ea72c38942b88e47584d99e64dd56a5
