### ISSUE TITLE
CardDAV Directory Gateway Extension

### ISSUE THREAD

**Issue by moimael** [miltonio/milton2#25]
Hi,

Is this draft RFC supported ? 
https://tools.ietf.org/html/draft-daboo-carddav-directory-gateway-02#page-4

It is implemented by apple devices to allow searching in a global directory without syncing everything.

If so do you have any pointer on how to use it in milton ?

**Comment by RobWin** [comment]
How can I disable the CardDAV Directory Gateway Extension?
By default each AddressBook is a Directory Gateway. Why is that?

**Comment by bradmac** [comment]
@RobWin yes, that doesnt look right to me. I would expect that we have an annotation to support returning an explicit gateway directory href, Eg

@DirectoryGateway
public HrefList getMyDirectoryGateways(User user) {
   ...
}

Then the AnnoPrincipalResource implementation would change to
	@Override
	public HrefList getDirectoryGateway() {
		log.trace("getSupportedComponentSets");
		return annoFactory.directoryGateway.get(this);
	}

@dachristensen does that sound reasonable, or is there some particular reason for returning users personal address books default gateways?

**Comment by dachristensen** [comment]
That sounds correct to me. Not every address book is a directory gateway. But I'm not using the annotation framework, so I don't think that this impacts me. Maybe @moimael can weigh in, since he submitted the original pull-request.

**Comment by bradmac** [comment]
ah yes, i didnt scroll back far enough :)

**Comment by RobWin** [comment]
Unfortunately the `CARDDAV:directory-gateway` property in a response causes the iOS client to issue the next requests of the autodiscovery with a WebDAV  header `Depth: 0`. Because of this the client does not get its default addressbook.

**Comment by bradmac** [comment]
OK, I'll disable that shortly and then look at introducing a new annotation to allow it for certain addressbooks only

**Comment by RobWin** [comment]
Thx!

**Comment by RobWin** [comment]
Any news regarding this issue?

**Comment by bradmac** [comment]
Not yet, but i dont have anything planned for the weekend....

**Comment by RobWin** [comment]
Would be nice, because we bought licenses :)
It stops us from using the latest version.

**Comment by bradmac** [comment]
Yes, will get onto it ASAP.

**Comment by bradmac** [comment]
Implementing as a per address book property. Eg:

@DirectoryGateway
public boolean isGateway(MyAddressBook ab) {
      return ab.isGateway(); // can be a constant or per addressbook
}

**Comment by bradmac** [comment]
Used in AnnoPrincipalResource like this:
````
	@Override
	public HrefList getDirectoryGateway() {
		try {
			HrefList list = new HrefList();
			// add all addressbooks which have the 
			for (Resource r : getChildren()) {
				if (r instanceof AnnoCollectionResource) {
					AnnoCollectionResource col = (AnnoCollectionResource) r;
					Boolean isDirectoryGateway = annoFactory.directoryGatewayAnnotationHandler.get(col);
					if ( isDirectoryGateway != null && isDirectoryGateway ) {
						list.add(col.getHref());
					}
				}
			}
			return list;
		} catch (NotAuthorizedException e) {
			throw new RuntimeException(e);
		} catch (BadRequestException e) {
			throw new RuntimeException(e);
		}
	}
````

**Comment by RobWin** [comment]
Thx

**Comment by bradmac** [comment]
Built and deployed 2.7.0.1 with this fix
