### ISSUE TITLE
Milton Client not parsing WebDav response correctly

### ISSUE THREAD

**Issue by RobWin** [miltonio/milton2#34]
Hello,

the Milton client does not parse WebDab prop-Elements correctly. The href is not parsed correctly.

Example:

```
<d:multistatus xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:card="urn:ietf:params:xml:ns:carddav" xmlns:d="DAV:">
    <d:response>
        <d:href>/spica-contacts/carddav/</d:href>
        <d:propstat>
            <d:prop>
                <d:resourcetype>
                    <d:collection/>
                </d:resourcetype>
                <d:current-user-principal>
                    <d:href>/spica-contacts/carddav/principals/dummyUser/</d:href>
                </d:current-user-principal>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
    </d:response>
</d:multistatus>
```

The problem lies in class PropFindResponse in line 82.

```
 String value = elProp.getText();
```

The element "current-user-principal" has a child property "href" instead of a String value.

Kind regards,

Robert Winkler

**Comment by RobWin** [comment]
Not active dev anymore?

**Comment by peteanusergiu** [comment]
Hello,

is there any progress on the above described issue? Before hacking the code and overwriting the "problematic" classes, it would help knowing if an update is planned in the near future.

Many thanks.

**Comment by bradmac** [comment]
Closing old issue. Please reopen if you would like assistance.
