### ISSUE TITLE
Server incorrectly handles COPY operation without 'Overwrite' flag

### ISSUE THREAD

**Issue by zenektm** [miltonio/milton2#36]
According to the specification and comments in CopyHandler.processExistingResource() method missing 'Overwrite' flag should be interpreted as allowed. However CopyHandler.canOverwrite() method works differently.
The canOverwrite() method even has a workaround for Mac Finder not sending the flag, which is completely unnecessary if this method is fixed to work per the specification. Another WebDav client that doesn't send Overwrite flag is BitKinex.
Please also fix identical method in MoveHandler.

**Comment by bradmac** [comment]
Closing old issue. Please reopen if you would like assistance.
