### ISSUE TITLE
security regression in 2.6.4 release

### ISSUE THREAD

**Issue by jloupdef** [miltonio/milton2#45]
In the commit of the 14th of december for code quality improvement (release in version 2.6.4) the following modification has been made on file AccessControlListAnnotationHandler.java, l.132 :

-privs = new HashSet<Priviledge>();
+privs = EnumSet.allOf(Priviledge.class);

Basically, this means everybody using ACL will have all priviledges...
Sorry if i'm mistaken, i'm a beginner with milton2 and struggling with ACL until i saw this, reverted to version 2.6.3.5 and everything's is now perfect.

**Comment by bradmac** [comment]
There's some notes and different logic in the code now
```
		// BM: this shouldnt be here. We do want to grant all privs at this point, because nothing
		// explicit was found, but only if there is a current user. And privs should use Priviledge.ALL
		// rather then allOf(..) because we want to use the more concise, unexpanded, priviledge set
		//privs = EnumSet.allOf(Priviledge.class);
		if (curUser != null) {
			log.info("No explicit AccessControl annotation found, so defaulting to full access for logged in user");
			privs = new HashSet<Priviledge>();
			privs.add(Priviledge.ALL);
		}
		return privs;
```
