### ISSUE TITLE
Implement PROPPATCH

### ISSUE THREAD

**Issue by ysyelite** [miltonio/milton2#51]
An update to the calendar will be done as a PROPPATCH.

Hope to know when will you finish implement PROPPATCH support in annotations.

**Comment by dachristensen** [comment]
The annotations framework handles the PROPPATCH for the Display Name, Calendar Color and Calendar Order properties. For other properties you need to bypass the annotation framework. I believe that I worked around this by creating my own PropertySource and adding it to the extraPropertySources of the HttpManagerBuilder.

**Comment by ysyelite** [comment]
thank you very much dachristensen!
