### ISSUE TITLE
Possible attempted hacking sporadically prevent sync

### ISSUE THREAD

**Issue by moimael** [miltonio/milton2#54]
Since our last milton update we encounter regularly this error, particularly on caldav :

io.milton.http.http11.auth.CookieAuthenticationHandler.getUserUrl(257): Invalid userUrl hash, possible attempted hacking attempt. 

Sometimes the sync works, but sometimes it fails with this message. 

Any thoughts ?

Thanks !

**Comment by moimael** [comment]
Any news on this ? We have this error several thousand time a day.

**Comment by bradmac** [comment]
FYI, this occurs when the cookie authentication process fails. This could be because you're user principals are not located at their reported URL.

**Comment by dlevis85** [comment]
I need help on this becauses I'm encountering the same issue.
What do you mean for "you're user principals are not located at their reported URL"?
Give me an example of code.
In our Authorization class that rapresents the session
`public class Authorization implements UserDetails, DiscretePrincipal{
private UserSo userSo;
.....
 private String getHRef()
  {
    return "users/" + userSo.getId();
  }

  @Override
  public String getPrincipalURL() {
    return getHRef();
  }

  @Override
  public PrincipleId getIdenitifer() {
    return new HrefPrincipleId(getHRef());
  }

}`
Is there something wrong in this implementation of DiscretePrincipal?
