### ISSUE TITLE
NPE in ICalFormatter.parseEvent()

### ISSUE THREAD

**Issue by preisser5p** [miltonio/milton2#58]
Method parseEvent() dosn't check input valitity. If the data doesn't contain any VEVENT a NullPointerException occurs:

public void parseEvent(EventResource r, String data) throws IOException, ParserException {
    CalendarBuilder builder = new CalendarBuilder();
    Calendar calendar = builder.build(new ByteArrayInputStream(data.getBytes("UTF-8")));
    VEvent ev = this.event(calendar);

**Comment by bradmac** [comment]
Fixed
