### ISSUE TITLE
XXX NOT IMPLEMENTED XXX printed to System.out

### ISSUE THREAD

**Issue by dachristensen** [miltonio/milton2#61]
The PrincipalSearchPropertySetReport prints this message every time that it is run. The default implementation returns search properties of display name, email address, first name, last name, user type and calendar addresses. This is actually a reasonable default implementation.
I would be happy to submit a patch that either:
1. Removes the System.out.println()
2. Uses the log.debug() instead of System.out.println() so that it can be muted
3. Implement something like a PrincipalPropertySearchableResource that can be implemented to return the list of searchable properties for that resource.
4. Extend the PrincipalSearchService interface to include a method for returning the searchable properties and injecting the principal search service into the PrincipalSearchPropersetSetReport.
Any votes on which direction to go? Personally, I would go with Option 1, but I'd be happy to make the search properties configurable if someone else thinks it would be useful.

**Comment by bradmac** [comment]
> Removes the System.out.println()

Fixed
