### ISSUE TITLE
Packages scanning problem (reflection utils and package url protocol)

### ISSUE THREAD

**Issue by pnowy** [miltonio/milton2#62]
We are using the Milton community version 2.6.5.5 and we found the problem with the packages scanning for classes with Milton annotations (method ReflectionUtils#getClassNamesFromPackage). 

Inside this method the package protocol is checked and depends of protocol the correct logic for scanning is used. I assume that everything works fine in single war/jar file but in our enterprise application we have separated parts for web part and for mentioned web part the following package URL is returned:

`zip:C:/server/domain/...directories.../war/WEB-INF/lib/webpart.jar!/com/example/core/milton`

Unfortunately in this situation the protocol zip is returned and not jar (though that milton annotated classes are inside the jar file as you can see on the path) and the Milton (WebDav) controller is not initialized. It looks like as a serious problem and I think that it occurs on every application which contains a controller within embedded jar file (due to the protocol which is used for JAR files).

In my opinion the line for checking the protocol should also contains the **"zip"** value. The simplest solution:

```
if (packageURL.getProtocol().equals("jar") || packageURL.getProtocol().equals("zip")) {...}
```

**Comment by pnowy** [comment]
I've prepared the pull request (#63) with the solution of the problem. Meantime I found one additional problem there. See the detail on pull request.

**Comment by bradmac** [comment]
Looks good, thanks.
