### ISSUE TITLE
Unable to use slashes in object names

### ISSUE THREAD

**Issue by phxql** [miltonio/milton2#74]
Hi,

with the current version of Milton i'm unable to use objects which contain a `/` in their `@Name` annotated methods.

The URL in the `PROPFIND` listing is encoded correctly (using `%2F` instead of `/`), but when issuing a `GET` request Milton responds with 404.

This problem is caused by the following: In `ResourceHandlerHelper` line 87 the `UrlAdapter` is used to decode the URL. After that, the resource factory is called to resolve the resource. The resource factories use `Path.path()` to construct a Path object, which is done by splitting by `/`. Unfortunatelly the encoded slash has already been decoded. That means the url-encoding for the slash has no effect.

To solve the problem you need to change it to the follwing: First split the URL in parts, then url-decode the parts.

Snippet from the `AnnotationResourceFactory`:

```
    public Resource findFromRoot(AnnoCollectionResource rootFolder, Path p) throws NotAuthorizedException, BadRequestException {
        CollectionResource col = rootFolder;
        Resource r = null;
        for (String s : p.getParts()) {
                        // Url-decode the part. TODO: Use the UrlAdapter for that.
            String decodedPart = Utils.decodePath(s);

            if (col == null) {
                if (log.isTraceEnabled()) {
```

**Comment by RobWin** [comment]
+1

**Comment by bradmac** [comment]
Thanks for the analysis. Will try to action that over the next week.

**Comment by bradmac** [comment]
Closing old issue. Please reopen if you would like assistance.
