### ISSUE TITLE
Publish Artifacts to Maven Central

### ISSUE THREAD

**Issue by damnhandy** [miltonio/milton2#75]
It would be really helpful to have the artifacts published to Maven Central. By not having these artifacts in Maven Central, it prevents other projects from being published into Maven Central as well.  Is there an issue preventing these artifacts from being published there?

**Comment by bradmac** [comment]
Not really an issue, its just that whenever i've looked into it before it seems like quite a bureaucratic process. Its easier to just run our own.

**Comment by damnhandy** [comment]
This is a very big issue for products or projects using Milton that need to be available in Maven central. It's actually not as much of a pain as it sounds and I've got [my own project up there to](https://github.com/damnhandy/Handy-URI-Templates). The only bureaucratic piece us having Sonatype verifying who you are and that's it. 

If a dependency is not in Maven Central, by extension that project can't be in Maven Central. It's also not very helpful when/if the Milton repo is down. I only need to point to the NPM [unpublishgate](https://www.jfrog.com/blog/how-not-to-care-about-unpublishgate/) to highlight the problems of having a single repo out there. 

Right now, I'm in a situation where my firewall rules allow access to Maven Central and Ibiblio repos, but not Milton. It would be much smoother if Milton libraries were available in the public repos. Remember, they are mirrored to multiple repos.

**Comment by RobWin** [comment]
You can also use Bintray and JCenter. Much easier and can automatically sync to Maven Central

**Comment by bradmac** [comment]
:+1:

**Comment by jlarmstrong** [comment]
This was an issue when the milton site was down the other week. Any public repo would be good including bintray.

**Comment by bradmac** [comment]
Now in bintray - https://bintray.com/milton/Milton/milton/view

**Comment by damnhandy** [comment]
This wasn't quite what I had in mind. Part of the process is to get into the Maven central repo's so that we're not bound a specific repository if one is down. One should be able to get Milton from Maven Central, Bintray, http://uk.maven.org/maven2/, etc.. 

What has been done is basically renaming the repo URL, but it hasn't done much for distributing the artifacts to other servers. Additionally, it's broken the dependencies such that projects referencing Milton will no longer build due to hard-coded repository references. See #77 

If everything is published to a central repo, you will have no need to hard-code repository references.

**Comment by bradmac** [comment]
bintray syncs with maven central, so thats the next step.

the milton maven repo is still running, so existing projects should not be affected

**Comment by bradmac** [comment]
re-opening until synced to maven c
