### ISSUE TITLE
Support for resolving custom arguments for @ResourceController methods

### ISSUE THREAD

**Issue by oyvindhorneland** [miltonio/milton2#79]
Hi,

It would be nice to see support for additional implementation specific argument resolvers for @ResourceController methods. Would it be possible to add something like Spring's org.springframework.web.method.support.HandlerMethodArgumentResolver to AnnotationResourceFactory?

Øyvind

**Comment by bradmac** [comment]
Yep, should be possible. Invocation arguments are built here:

https://github.com/miltonio/milton2/blob/master/milton-server-ce/src/main/java/io/milton/http/annotated/AnnotationResourceFactory.java#L494

Basically all we do is stuff everything we have in context into an ordered list (some objects have precedence so go first), and then after a couple of hard coded checks we for each method parameter we cycle through the list looking for the first compatible:

```
	private Object findArgValue(Class type, Request request, Response response, List otherAvailValues) throws Exception {
		if (type == Request.class) {
			return request;
		} else if (type == Response.class) {
			return response;
		} else if (type == byte[].class) {
			InputStream in = (InputStream) findArgValue(InputStream.class, request, response, otherAvailValues);
			return toBytes(in);
		} else {
			for (Object o : otherAvailValues) {
				if (o != null && type.isAssignableFrom(o.getClass())) {
					otherAvailValues.remove(o); // remove it so that we dont use same value for next param of same type
					return o;
				}
			}
}
```
