### ISSUE TITLE
where can I download milton javadocs ?

### ISSUE THREAD

**Issue by abnud1** [miltonio/milton2#85]
I'm using intellij idea and I want to download the javadocs for `milton-server-ce`(and `milton-api` I suppose) so that intellij can recognize them.  

I'd optionally like to download javadocs for `milton-mail-server` and `milton-mail-api`.  

Now I'm actually using gradle But I don't mind to download javadocs manually.  

At downloads page I only see sources jars, I can browse the javadocs online but what I want is to download it.  

Are javadocs jars available somewhere ?

**Comment by dizzzz** [comment]
If you have the source-jars, then the javadoc-jars are not really required, right?

unfortunately `mvn javadoc:javadoc` does not work :-(

**Comment by abnud1** [comment]
@dizzzz sorry but autocomplete used to not work so I thought maybe the problem is missing javadocs-jar, the issue is resolved and as you said the sources.jar alone is enough, sorry for this :)
